=== L2jBrasil/Server-Interlude/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="ItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="ItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="skill" type="xmlItemSkill" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="xmlItemSkill">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="level" type="xs:int" default="1"/>
        <xs:attribute name="chance" type="xs:int" default="100"/>
        <xs:attribute name="triggerType" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/1600-1699.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='1660' name="cursed_maingauche">

        <stat function='add' value='62' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='42' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/8200-8299.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='8203' name="(monster_only)venom_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8204' name="(monster_only)frintessa_follower_calibur">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8205' name="(monster_only)heretic_priest_sickle">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8206' name="(monster_only)heretic_priest_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8207' name="(monster_only)heretic_privates_axe">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8208' name="(monster_only)heretic_privates_staff">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8209' name="(monster_only)lidia_von_helmanns_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8210' name="(monster_only)monk_warrior_shield">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='230' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>

    </item>
    <item id='8211' name="(monster_only)monk_warrior_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8212' name="(monster_only)solina_brother_mace">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8213' name="(monster_only)solina_father_mace">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8214' name="(monster_only)solina_priest_pole">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8215' name="(monster_only)zombie_enlisted_man_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='00' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8216' name="(monster_only)zombie_enlisted_man_claw">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8217' name="(monster_only)zombie_gateguard_spear">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8218' name="(monster_only)zombie_laborer_axe">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8219' name="(monster_only)zombie_laborer_sword">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8220' name="(monster_only)apostle_grail_bow">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8221' name="(monster_only)apostle_grail_spear">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='8222' name="(monster_only)frintessa_follower_tran_calibur">

        <stat function='add' value='0' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='0' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/7900-7999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='7900' name="ice_storm_hammer">

        <stat function='add' value='213' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='91' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='7901' name="star_buster">

        <stat function='add' value='236' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='99' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='7902' name="doom_crusher">

        <stat function='add' value='282' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='114' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='7903' name="(monster_only)frintessa_follower_calibur">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/6700-6799.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='6715' name="monster_only(silenos_archer)">

        <stat function='add' value='16' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6716' name="monster_only(silenos_shaman)">

        <stat function='add' value='11' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6717' name="monster_only(einhasad_warrior)">

        <stat function='add' value='24' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='17' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6718' name="monster_only(einhasad_shaman)">

        <stat function='add' value='24' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='17' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6719' name="monster_only(ketra_orc_chieftain)">

        <stat function='add' value='141' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='104' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6720' name="monster_only(shadow_of_halisha)">

        <stat function='add' value='16' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6721' name="monster_only(shield_of_imperial_warlord">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='47' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
        <stat function='enchant' value='0' order='12' name='SHIELD_DEFENCE'/>

    </item>
    <item id='6722' name="monster_only(ahrimanes)">

        <stat function='add' value='236' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='99' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='6723' name="monster_only(vampire_warrior)">

        <stat function='add' value='112' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='54' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/armor/6600-6699.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='6656' name="Earring of Antharas">

        <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='31' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6657' name="Necklace of Valakas">

        <stat function='add' value='95' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='42' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6658' name="Ring of Baium">

        <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='21' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6659' name="Zaken's Earring">

        <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='31' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6660' name="Ring of Queen Ant">

        <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='21' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6661' name="Earring of Orfen">

        <stat function='add' value='71' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='31' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6662' name="Ring of Core">

        <stat function='add' value='48' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='21' order='64' name='MAX_MP'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6674' name="Sealed Imperial Crusader Breastplate">

        <stat function='add' value='193' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6675' name="Sealed Imperial Crusader Gaiters">

        <stat function='add' value='121' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6676' name="Sealed Imperial Crusader Gauntlet">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6677' name="Sealed Imperial Crusader Boots">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6679' name="Sealed Imperial Crusader Helmet">

        <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6680' name="Sealed Draconic Leather Armor">

        <stat function='add' value='236' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6681' name="Sealed Draconic Leather Glove">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6682' name="Sealed Draconic Leather Boots">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6683' name="Sealed Draconic Leather Helmet">

        <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6684' name="Sealed Major Arcana Robe">

        <stat function='add' value='157' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6685' name="Sealed Major Arcana Glove">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6686' name="Sealed Major Arcana Boots">

        <stat function='add' value='55' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6687' name="Sealed Major Arcana Circlet">

        <stat function='add' value='83' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='6724' name="Sealed Tateossian Earring">

        <stat function='add' value='68' order='16' name='MAGIC_DEFENCE'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6725' name="Sealed Tateossian Ring">

        <stat function='add' value='46' order='16' name='MAGIC_DEFENCE'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
    <item id='6726' name="Sealed Tateossian Necklace">

        <stat function='add' value='91' order='16' name='MAGIC_DEFENCE'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_DEFENCE'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/9100-9199.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='9129' name="Shadow Weapon: Shield of Nightmare">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='256' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>

    </item>
    <item id='9136' name="Sword of Valakas (1-Handed)">

        <stat function='add' value='156' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='83' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='9137' name="Sword of Valakas (2-Handed)">

        <stat function='add' value='78' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='39' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='9140' name="Cupid\'s Bow">

        <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='9141' name="Cupid\'s Bow - Event Use">

        <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
</itemList>
