=== L2jBrasil/Server-Interlude/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="ItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="ItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="skill" type="xmlItemSkill" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="xmlItemSkill">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="level" type="xs:int" default="1"/>
        <xs:attribute name="chance" type="xs:int" default="100"/>
        <xs:attribute name="triggerType" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/8600-8699.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='8678' name="Sirra\'s Blade">

        <stat function='add' value='251' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8679' name="Sword of Ipos">

        <stat function='add' value='305' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8680' name="Barakiel\'s Axe">

        <stat function='add' value='251' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8681' name="Behemoth\'s Tuning Fork">

        <stat function='add' value='305' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8682' name="Naga Storm">

        <stat function='add' value='220' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8683' name="Tiphon\'s Spear">

        <stat function='add' value='251' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='add' value='66' order='8' name='PHYSIC_ATTACK_RANGE'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8684' name="Shyeed\'s Bow">

        <stat function='add' value='570' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='133' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='227' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8685' name="Sobekk\'s Hurricane">

        <stat function='add' value='305' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='121' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8686' name="Themis\' Tongue">

        <stat function='add' value='202' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='161' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8687' name="Cabrio\'s Hand">

        <stat function='add' value='202' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='161' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8688' name="Daimon Crystal">

        <stat function='add' value='245' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='161' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='8689' name="Blood Sword Akamanah">

        <stat function='add' value='361' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='137' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/4200-4299.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='4202' name="chrono_cithara">

        <stat function='add' value='1' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='1' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4219' name="dream_sword">

        <stat function='add' value='31' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4220' name="dream_knife">

        <stat function='add' value='27' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4221' name="ubiquitous_axe">

        <stat function='add' value='31' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='21' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4222' name="dream_shield">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='90' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='4223' name="ubiquitous_shield">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='90' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='4233' name="knuckle_duster">

        <stat function='add' value='148' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='68' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4237' name="hatchlings_level_65_weapon">

        <stat function='add' value='24' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='32' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
    <item id='4238' name="hatchlings_level_75_weapon">

        <stat function='add' value='31' order='16' name='PHYSIC_ATTACK'/>
        <stat function='add' value='43' order='16' name='MAGIC_ATTACK'/>
        <stat function='add' value='80' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='304' order='8' name='PHYSIC_ATTACK_SPEED'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/armor/0100-0299.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='112' name="Apprentice's Earring">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='11'/>
    </item>

    <item id='113' name="Mystic's Earring">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='13'/>
    </item>

    <item id='114' name="Earring of Strength">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='16'/>
    </item>

    <item id='115' name="Earring of Wisdom">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='16'/>
    </item>

    <item id='116' name="Magic Ring">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='7'/>
    </item>

    <item id='117' name="Ring of Mana">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='34'/>
        <stat function="enchant" order='12' name='MAGIC_DEFENCE' value='0'/>
    </item>

    <item id='118' name="Necklace of Magic">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='15'/>
    </item>

    <item id='119' name="Necklace of Binding">
        <stat function="add" order='16' name='MAGIC_DEFENCE' value='64'/>
        <stat function="enchant" order='12' name='MAGIC_DEFENCE' value='0'/>
    </item>

</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/armor/0000-0099.xml
<?xml version='1.0' encoding='utf-8'?>

<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='21' name="Shirt">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='36'/>
    </item>

    <item id='22' name="Leather Shirt">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='43'/>
    </item>

    <item id='23' name="Wooden Breastplate">
        <stat function="add" order='16' name='PHYSIC_DEFENCE' value='47'/>
    </item>

    <item id='24' name="Bone Breastplate">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='50'/>
    </item>

    <item id='25' name="Piece Bone Breastplate">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='62'/>
    </item>

    <item id='26' name="Bronze Breastplate">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='68'/>
    </item>

    <item id='27' name="Hard Leather Shirt">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='53'/>
    </item>

    <item id='28' name="Pants">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='22'/>
    </item>

    <item id='29' name="Leather Pants">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='27'/>
    </item>

    <item id='30' name="Hard Leather Pants">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='29'/>
    </item>

    <item id='31' name="Bone Gaiters">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='32'/>
    </item>

    <item id='32' name="Piece Bone Gaiters">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='39'/>
    </item>

    <item id='33' name="Hard Leather Gaiters">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='33'/>
    </item>

    <item id='34' name="Bronze Gaiters">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='43'/>
    </item>

    <item id='35' name="Cloth Shoes">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='9'/>
    </item>

    <item id='36' name="Leather Sandals">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='9'/>
    </item>

    <item id='37' name="Leather Shoes">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='13'/>
    </item>

    <item id='38' name="Low Boots">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='15'/>
    </item>

    <item id='39' name="Boots">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='17'/>
    </item>

    <item id='40' name="Leather Boots">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='19'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='41' name="Cloth Cap">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='13'/>
    </item>

    <item id='42' name="Leather Cap">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='16'/>
    </item>

    <item id='43' name="Wooden Helmet">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='19'/>
    </item>

    <item id='44' name="Leather Helmet">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='23'/>
    </item>

    <item id='45' name="Bone Helmet">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='29'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='46' name="Bronze Helmet">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='33'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='47' name="Helmet">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='37'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='48' name="Short Gloves">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='9'/>
    </item>

    <item id='49' name="Gloves">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='13'/>
    </item>

    <item id='50' name="Leather Gloves">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='15'/>
    </item>

    <item id='51' name="Bracer">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='17'/>
    </item>

    <item id='52' name="Hemp Cloak">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='2'/>
    </item>

    <item id='53' name="Cotton Cloak">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='3'/>
    </item>

    <item id='54' name="Silk Cloak">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='4'/>
    </item>

    <item id='55' name="Cotton Undergarment">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='4'/>
    </item>

    <item id='56' name="Wool Undergarment">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='5'/>
    </item>

    <item id='58' name="Mithril Breastplate">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='95'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='59' name="Mithril Gaiters">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='61'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='60' name="Composite Armor">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='224'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='61' name="Mithril Gloves">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='29'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='62' name="Mithril Boots">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='32'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='63' name="Gauntlets">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='24'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

    <item id='64' name="Composite Boots">
        <stat function="add" name='PHYSIC_DEFENCE' order='16' value='36'/>
        <stat function="enchant" name='PHYSIC_DEFENCE' order='12' value='0'/>
    </item>

</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/0900-0999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='945' name="skeleton_buckler">

        <stat function='sub' value='8' order='16' name='EVASION_RATE'/>
        <stat function='add' value='69' order='8' name='SHIELD_DEFENCE'/>
        <stat function='add' value='20' order='8' name='SHIELD_RATE'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='946' name="skeleton_dagger">

        <stat function='add' value='16' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='13' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='975' name="blood_saber">

        <stat function='add' value='14' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='11' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='981' name="red_sunset_sword">

        <stat function='add' value='16' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='989' name="eldritch_dagger">

        <stat function='add' value='11' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='10' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='433' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/1200-1299.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='1213' name="guards_bow">

        <stat function='add' value='49' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='17' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='12' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='-3' order='16' name='ACCURACY'/>
        <stat function='add' value='293' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='1295' name="long_sword">

        <stat function='add' value='22' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='1296' name="gladius">

        <stat function='add' value='22' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='1297' name="bastard_sword">

        <stat function='add' value='22' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='1298' name="caliburs">

        <stat function='add' value='22' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='379' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='1299' name="great_sword">

        <stat function='add' value='200' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='6' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='8' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='0' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>
