=== L2jBrasil/Server-Interlude/Datapack/data/stats/item.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://la2j.org"
           xmlns="http://la2j.org"
           elementFormDefault="qualified">

    <xs:include schemaLocation="stat.xsd"/>

    <xs:element name="itemList">
        <xs:complexType>
            <xs:choice>
                <xs:element name="item" type="ItemStat" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:complexType>

    </xs:element>

    <xs:complexType name="ItemStat">
        <xs:sequence>
            <xs:element name="stat" type="xmlTypeStat" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="skill" type="xmlItemSkill" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="xmlItemSkill">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="level" type="xs:int" default="1"/>
        <xs:attribute name="chance" type="xs:int" default="100"/>
        <xs:attribute name="triggerType" type="xs:string" use="required"/>
    </xs:complexType>

</xs:schema>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/armor/8500-8599.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns="http://la2j.org" xsi:schemaLocation="http://la2j.org ../item.xsd">

    <item id='8541' name="Little Harness">

        <stat function='add' value='25' order='16' name='MAGIC_DEFENCE'/>
        <stat function='add' value='10' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8552' name="Mask of Spirits">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8557' name="Blue Party Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8558' name="Eva's Mark">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8559' name="Diadem">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8560' name="Teddy Bear Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8561' name="Piggy Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8562' name="Jester Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8563' name="Wizard's Hat">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8564' name="Dapper Cap">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8565' name="Romantic Chapeau">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8566' name="Iron Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8567' name="valueakas Slayer Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8568' name="Antharas Slayer Circlet">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
    <item id='8569' name="Half Face Mask">

        <stat function='add' value='0' order='16' name='PHYSIC_DEFENCE'/>

    </item>
</itemList>

=== L2jBrasil/Server-Interlude/Datapack/data/stats/weapon/4900-4999.xml
<?xml version='1.0' encoding='utf-8'?>
<itemList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://la2j.org"
          xsi:schemaLocation="http://la2j.org ../item.xsd">
    <item id='4900' name="staff_of_evil_spirit_magic_focus">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Magic Focus -->
        <skill triggerType="onCast" id='1077' level='3' chance='20'/>

    </item>
    <item id='4901' name="staff_of_evil_spirit_bodily_blessing">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <!-- Bodily Blessing -->
        <skill triggerType='onCast' id='1045' level='5' chance='20'/>

    </item>
    <item id='4902' name="staff_of_evil_spirit_magic_poison">

        <stat function='add' value='189' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='132' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <skill id="1168" triggerType="onCast" level="6" chance="6"/>

    </item>
    <item id='4903' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>
        <stat function='mul' value='1.25' order='48' name='MAX_HP'/>

    </item>
    <item id='4904' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
    <item id='4905' name="dasparions_staff">

        <stat function='add' value='207' order='8' name='PHYSIC_ATTACK'/>
        <stat function='add' value='143' order='8' name='MAGIC_ATTACK'/>
        <stat function='add' value='4' order='8' name='CRITICAL_RATE'/>
        <stat function='add' value='4' order='16' name='ACCURACY'/>
        <stat function='add' value='325' order='8' name='PHYSIC_ATTACK_SPEED'/>
        <stat function='enchant' value='0' order='12' name='PHYSIC_ATTACK'/>
        <stat function='enchant' value='0' order='12' name='MAGIC_ATTACK'/>

    </item>
</itemList>
